# Generated by Django 3.0.4 on 2020-03-26 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('device_type', models.CharField(choices=[('Outlet', 'Room_Outlet_Controller'), ('Camera', 'Room_Camera'), ('Lock', 'Room_Lock_Controller'), ('Motion', 'Room_Motion_Sensor'), ('Temperature', 'Room_Temperature_Sensor')], max_length=40)),
                ('device_name', models.CharField(max_length=40)),
                ('device_label', models.CharField(max_length=40)),
                ('device_description', models.TextField()),
                ('location_id', models.CharField(max_length=40)),
                ('complete_setup', models.BooleanField()),
                ('hub_id', models.CharField(max_length=40)),
                ('network_type', models.CharField(choices=[('ZIGBEE', 'ZIGBEE'), ('ZWAVE', 'ZWAVE')], max_length=40)),
                ('network_sec', models.CharField(max_length=40)),
                ('create_by', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('face_embedding', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('identity', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('create_by', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('room_description', models.TextField()),
                ('create_by', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actuator', models.CharField(max_length=100)),
                ('configuration', models.CharField(max_length=255)),
                ('health_check', models.TextField()),
                ('refresh', models.CharField(max_length=40)),
                ('sensor', models.CharField(max_length=40)),
                ('battery_value', models.FloatField()),
                ('lock_data', models.CharField(max_length=40)),
                ('lock_value', models.CharField(max_length=40)),
                ('motion_sensor_value', models.CharField(max_length=10)),
                ('temperature_unit', models.CharField(choices=[('F', 'Fahrenheit'), ('C', 'Celsius')], max_length=10)),
                ('temperature_value', models.FloatField()),
                ('power_unit', models.CharField(choices=[('W', 'Watts')], max_length=10)),
                ('power_value', models.FloatField()),
                ('holdable_button', models.CharField(max_length=10)),
                ('outlet_switch_value', models.CharField(max_length=10)),
                ('create_by', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.Device')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.Room'),
        ),
    ]
