# Generated by Django 3.0.4 on 2020-03-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='room',
            field=models.CharField(max_length=40),
        ),
    ]
