# Generated by Django 3.0.4 on 2020-03-31 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_auto_20200330_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.CharField(max_length=40)),
                ('person_name', models.CharField(max_length=40)),
                ('record_time', models.DateTimeField(auto_now_add=True)),
                ('face_encoding', models.TextField()),
                ('camera_id', models.TextField()),
            ],
        ),
    ]
