# Generated by Django 3.0.4 on 2020-04-02 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_camerarecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camerarecord',
            name='face_encoding',
        ),
        migrations.RemoveField(
            model_name='person',
            name='create_by',
        ),
    ]
