# Generated by Django 3.0.4 on 2020-04-02 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_auto_20200402_0246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='create_by',
        ),
    ]
