# Generated by Django 3.0.4 on 2020-04-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_remove_device_create_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedata',
            name='device',
            field=models.CharField(max_length=40),
        ),
    ]
