# Generated by Django 3.0.4 on 2020-04-02 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0006_auto_20200402_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedata',
            name='face_email',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicedata',
            name='face_name',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
