# Generated by Django 3.0.4 on 2020-04-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0007_auto_20200402_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField()),
                ('sensor_data', models.TextField()),
                ('created_by', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
